### ISSUE TITLE
The field type "location" does not exist

### ISSUE THREAD

**Issue by medienbaecker** [sylvainjule/kirby-locator#5] opened 2018-11-15 14:07 UTC
While the plugin is correctly installed (and other plugins work fine) I somethow get the following error message with the latest nightly build:

![image](https://user-images.githubusercontent.com/7975568/48557780-f0cf3180-e8e7-11e8-9726-37c6be5e8a27.png)

"location" is the field name, not field type, in this case:

```yaml
fields:
  location:
    type: locator
```

**Comment by sylvainjule** [comment] 2018-11-15 14:21
It's probably an issue with the build process. Sometimes I have to rebuild plugins in new installs but I haven't found out why yet.

Could you try running `npm install` + `npm run build` in the plugin's folder to see if it fixes this?

**Comment by medienbaecker** [comment] 2018-11-15 14:30
That does indeed fix the error. Thanks Sylvain!

I think Bastian changed some things regarding the localization in this nightly, I now only get the variables. Or is that something else entirely?

![image](https://user-images.githubusercontent.com/7975568/48559148-4bb65800-e8eb-11e8-9451-5e375d609f32.png)

**Comment by sylvainjule** [comment] 2018-11-15 14:43
Oh, that's weird. I have no issue with translations with the latest nightly.

No errors thrown? Do you have another plugin successfully loading translated strings?

Sorry for the chaotic start, not quite plug-and-play yet 😶

**Comment by medienbaecker** [comment] 2018-11-15 14:47
Changing my panel language from "German" to "Français" or "English" works. But I think the language fallback shouldn't be the language variables. Much rather just English.

No need to be sorry, it's a very well made plugin. My current Kirby 3 process is "write 2 lines of code, add 1 issue" anyway 😅

**Comment by sylvainjule** [comment] 2018-11-15 14:59
Should have thought about the missing language. That's a sneaky subterfuge to incite translations 😅

Thanks for reminding me, I wanted to ask for a global fix but it slipped off my mind. I will open a ticket, I think having a fallback to English should be set up globally rather than for each plugin.

**Comment by sylvainjule** [comment] 2018-11-19 10:46
Closing this as it's not caused by the plugin itself.
Opened an issue about it [here](https://github.com/k-next/kirby/issues/1200).

**Closed by sylvainjule** 2018-11-19 10:46 UTC
